apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: mongodb
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        cronjob: mongodb-backup
    spec:
      template:
        metadata:
          labels:
            cronjob: mongodb-backup
        spec:
          volumes:
          - name: gcloud-backup-sa
            secret:
              secretName: gcloud-backup-sa
              items:
              - key: sa.json
                path: sa.json
          containers:
          - name: mongodb-backup
            image: {{ .Values.image.name }}:{{ .Values.image.version }}
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: mongodb-backup-config
            volumeMounts:
            - name: gcloud-backup-sa
              readOnly: true
              mountPath: "/usr/src/app/sa.json"
              subPath: "sa.json"
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: regcred-googlecontainerregistry