apiVersion: v1
kind: Secret
metadata:
  name: mongodb-backup-config
  namespace: mongodb
type: Opaque
stringData:
  gcloud_project: "{{.Values.gcloud.project}}"
  gcloud_bucket: "{{.Values.gcloud.bucket}}"
  mongo_username: "{{.Values.mongo.username}}"
  mongo_password: "{{.Values.mongo.password}}"
  mongo_server: "{{.Values.mongo.server}}"
